### ISSUE TITLE
`sls deploy` prints "Unable to find any running pod for <xxxxx>. Retrying..."

### ISSUE THREAD

**Issue by ccll** [serverless/serverless-kubeless#77]
The deployment is indeed successful, despite the error message.
Seems that the detection of the deployed pod failed, so serverless-kubeless keeps printing the error message and creating new pods.
With `kubectl get pod` I can see there is one function pod in `Running` status and several in `Terminating` status.

![image](https://user-images.githubusercontent.com/5366582/32206344-6d5366d4-be2f-11e7-9e6a-f5165cb436cc.png)

My environment:
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

$ npm -v
3.10.10

$ node -v
v6.11.5

$ sls -v
1.23.0

$ kubeless version
Kubeless version: v0.2.3 (bfefb404)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ cat package.json 
{
  "name": "kubeless-python",
  "version": "1.0.0",
  "description": "Sample Kubeless Python serverless framework service.",
  "dependencies": {
    "serverless-kubeless": "^0.2.2"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "serverless",
    "kubeless"
  ],
  "author": "The Kubeless Authors",
  "license": "Apache-2.0"
}

```

**Comment by andresmgot** [comment]
Hi @ccll,
That error is triggered when the are no pods with the label `function=<function_name>` or when the creation timestamp is older than the moment in which the creation request is made (in order to avoid old deployments as new). Sometimes the clock between the cluster and the client gets misconfigured.

Can you check if when you deploy a new pod it gets created with an `AGE` greater than 0 seconds?

Also, in your screenshot there are several pods (Running and Terminating), are all those pods related to the same function? (only one should be there)

**Comment by ccll** [comment]
@andresmgot Yes, the clock is exactly the problem!
My client clock is several seconds ahead of the cluster, after re-sync the clock the issue disappears.

And it also turns out the multiple pods of the same function is caused by kubeless, the same behavior is observed when deploying the function with the `kubeless` CLI.

Thanks very much for the help, issue closed.
